clean up logging and service restart logic

diff --git a/etc/service/hydrator/run b/etc/service/hydrator/run
--- a/etc/service/hydrator/run
+++ b/etc/service/hydrator/run
@@ -1,4 +1,9 @@
 #!/bin/sh
 exec 2>&1
 source /etc/envvars
-exec /usr/bin/hydrator
+echo " ---- starting hydrator "
+/usr/bin/hydrator
+if [ $? -ne 0 ]; then
+  echo " ---- unable to start hydrator (sleeping 5 seconds) "
+  sleep 5 
+fi
diff --git a/etc/service/nginx/run b/etc/service/nginx/run
--- a/etc/service/nginx/run
+++ b/etc/service/nginx/run
@@ -1,4 +1,9 @@
 #!/bin/sh
 exec 2>&1
 source /etc/envvars
-exec /usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;"
+echo " ==== starting 'nginx -c /etc/nginx/nginx.conf' "
+/usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;" 
+if [ $? -ne 0 ]; then
+  echo " ==== unable to start 'nginx -c /etc/nginx/nginx.conf' (sleeping 30 seconds) " 
+  sleep 30 
+fi
